import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fffbff",
        "on-surface": "#3a3a00",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#f5f5dc",
        "secondary-fixed": "#e1e1f5",
        "on-error-container": "#6e0523",
        "on-tertiary-fixed": "#494b39",
        "secondary-container": "#e1e1f5",
        "primary": "#875763",
        "surface-container-high": "#f2f2ad",
        "on-tertiary-container": "#5c5d4a",
        "on-primary-fixed-variant": "#6a3e49",
        "on-tertiary-fixed-variant": "#666854",
        "on-secondary-fixed": "#3d3e4e",
        "tertiary": "#646652",
        "tertiary-container": "#f5f5dc",
        "inverse-surface": "#0f0f00",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#603541",
        "error-container": "#f97386",
        "error-dim": "#6b0221",
        "surface-bright": "#fffbff",
        "secondary-dim": "#565768",
        "on-secondary-container": "#4f5161",
        "outline": "#848442",
        "surface-container-low": "#fefcc4",
        "secondary": "#626374",
        "surface": "#fffbff",
        "inverse-on-surface": "#a09f78",
        "on-primary-fixed": "#49222d",
        "surface-tint": "#875763",
        "outline-variant": "#bdbd75",
        "surface-container-highest": "#edec9f",
        "on-surface-variant": "#676729",
        "on-secondary-fixed-variant": "#595a6b",
        "on-primary": "#ffffff",
        "primary-fixed": "#f5b9c7",
        "tertiary-dim": "#585a47",
        "primary-container": "#f5b9c7",
        "error": "#af3b50",
        "primary-dim": "#794b57",
        "surface-container": "#f8f7b7",
        "surface-variant": "#edec9f",
        "on-background": "#3a3a00",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#f5b9c7",
        "primary-fixed-dim": "#e6acb9",
        "tertiary-fixed-dim": "#e7e7ce",
        "secondary-fixed-dim": "#d3d3e6",
        "surface-dim": "#e7e79a"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "serif": ["Noto Serif", "serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [forms, containerQueries],
};
